/**
 * This code was generated by Builder.io
 */
import SwiftUI

struct BottomImageView: View {
    var body: some View {
        AsyncImage(url: URL(string: "https://cdn.builder.io/api/v1/image/assets/54ff05a6170d40a68992a4d816d1e6d4/12fc6086fc88e1ddac5d6fb91ad66813629ca2641da516608acc88a37aa42ee8?apiKey=54ff05a6170d40a68992a4d816d1e6d4&&format=webp")) { image in
            image.resizable()
                .aspectRatio(0.95, contentMode: .fit)
                .frame(maxWidth: 185)
        } placeholder: {
            Color.gray
        }
        .padding(.top, 7)
        .padding(.trailing, 78)
        .background(Color.white)
        .cornerRadius(24)
        .overlay(
            RoundedRectangle(cornerRadius: 24)
                .stroke(Color.white.opacity(0.1), lineWidth: 1)
        )
    }
}
