/**
 * This code was generated by Builder.io
 */
import SwiftUI

struct EventsGrid: View {
    var body: some View {
        HStack(spacing: 20) {
            EventCard(imageURL: "https://cdn.builder.io/api/v1/image/assets/54ff05a6170d40a68992a4d816d1e6d4/d6821263b2091e2fbee352e3f3f117ab166fd4df514a3241164add22c9b2ff5e?apiKey=54ff05a6170d40a68992a4d816d1e6d4&&format=webp", title: "")
            EventCard(imageURL: "https://cdn.builder.io/api/v1/image/assets/54ff05a6170d40a68992a4d816d1e6d4/2aaa46aa62ccc7c8da3bbdf50e79b51b868ed198f563181377fbd5349467d737?apiKey=54ff05a6170d40a68992a4d816d1e6d4&&format=webp", title: "Sonic Odyssey: Journey Through Time and Space")
        }
        .padding(.top, 20)
    }
}

struct EventCard: View {
    let imageURL: String
    let title: String
    
    var body: some View {
        VStack(alignment: .leading) {
            ZStack(alignment: .topTrailing) {
                AsyncImage(url: URL(string: imageURL + "&format=webp")) { image in
                    image.resizable()
                } placeholder: {
                    Color.gray
                }
                .aspectRatio(contentMode: .fill)
                
                Image(systemName: "heart")
                    .foregroundColor(.white)
                    .padding(8)
                    .background(Color.white.opacity(0.1))
                    .clipShape(Circle())
                    .padding(12)
            }
            
            if !title.isEmpty {
                Text(title)
                    .font(.custom("Lexend", size: 14).weight(.medium))
                    .foregroundColor(Color(red: 0.97, green: 0.98, blue: 0.99))
                    .padding(12)
            }
        }
        .background(Color.white)
        .cornerRadius(24)
        .overlay(
            RoundedRectangle(cornerRadius: 24)
                .stroke(Color.white.opacity(0.1), lineWidth: 1)
        )
    }
}