/**
 * This code was generated by Builder.io
 */
import SwiftUI

struct UpcomingEventsSection: View {
    var body: some View {
        HStack {
            Text("Upcoming Events")
                .font(.custom("Lexend", size: 20))
                .foregroundColor(Color(red: 0.89, green: 0.91, blue: 0.94))
            Spacer()
            Text("See all")
                .font(.custom("Lexend", size: 14).weight(.light))
                .foregroundColor(Color(red: 0.58, green: 0.64, blue: 0.72))
        }
        .padding(.top, 40)
    }
}